### ISSUE TITLE
single docker-compose run 

### ISSUE THREAD

**Issue by siavashfazli** [Phuker/docker-compose-all#1]
hi! 
I want to run a single docker-compose file in specified directory.
what does the code in python library?
Thanks for your help.

**Comment by Phuker** [comment]
This tool is not necessary if you only need to run one Docker Compose project. You can use the original `docker-compose` command, just `cd` into the directory, and then run `docker-compose up -d`.

If you want to use this tool in anyway, run: `docker-compose-all --up /path/to/that/directory `
